// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

package projectconfig

import (
	"errors"
	"fmt"
	"path/filepath"
	"slices"
	"sort"
	"strings"

	"dario.cat/mergo"
	"github.com/brunoga/deep"
	"github.com/microsoft/azure-linux-dev-tools/internal/rpm"
	"github.com/microsoft/azure-linux-dev-tools/internal/utils/fileutils"
)

// ErrUndefinedComponent is returned when a component group references a component name
// that is not defined in the project's top-level components map.
var ErrUndefinedComponent = errors.New("undefined component reference")

const (
	// HashTypeSHA256 represents the SHA-256 hash algorithm.
	HashTypeSHA256 = fileutils.HashTypeSHA256

	// HashTypeSHA512 represents the SHA-512 hash algorithm.
	HashTypeSHA512 = fileutils.HashTypeSHA512
)

// ComponentReference encapsulates a reference to a source component.
type ComponentReference struct {
	// Name of the component.
	Name string

	// Version of the component (optional).
	Version *rpm.Version
}

// OriginType indicates the type of origin for a source file.
type OriginType string

const (
	// OriginTypeURI indicates that the source file is fetched from a URI.
	OriginTypeURI OriginType = "download"

	// OriginTypeCustom indicates that the source file is generated by running a local
	// shell script inside a mock chroot. The script is expected to populate a specific
	// output directory; azldev then packages that directory into a deterministic archive.
	OriginTypeCustom OriginType = "custom"

	// OriginTypeOverlay indicates that the source file's hash was changed by archive overlays.
	// No download occurs; the file is already present as a spec source. The 'hash' and 'hash-type'
	// fields record the expected post-overlay hash, or can be omitted temporarily with
	// '--allow-no-hashes' while source preparation computes the initial value.
	OriginTypeOverlay OriginType = "overlay"
)

// IsFetched reports whether [SourceManager.FetchFiles] downloads this origin type to disk.
// Returns false for [OriginTypeOverlay], which obtains its file via the upstream lookaside
// extractor in [SourceManager.FetchComponent]. All other types return true.
func (t OriginType) IsFetched() bool {
	return t != OriginTypeOverlay
}

// Origin describes where a source file comes from and how to retrieve it.
// An origin is required for every 'source-files' entry.
type Origin struct {
	// Type indicates how the source file should be acquired.
	Type OriginType `toml:"type" json:"type" jsonschema:"required,enum=download,enum=custom,enum=overlay,title=Origin type,description=Type of origin for this source file" fingerprint:"-"`
	// Uri to download the source file from if origin type is 'download'. Ignored for other origin types.
	Uri string `toml:"uri,omitempty" json:"uri,omitempty" jsonschema:"title=URI,description=URI to download the source file from if origin type is 'download',example=https://example.com/source.tar.gz" fingerprint:"-"`

	// Script is the plain filename, with no path separators, of a shell script run inside a mock
	// chroot to generate this source file.
	// For upstream components it is relative to the declaring config file; for local components
	// it is relative to the component's spec directory.
	// Required when [Origin.Type] is 'custom'; must be empty otherwise.
	Script string `toml:"script,omitempty" json:"script,omitempty" jsonschema:"title=Script,description=Plain shell script filename with no path separators. Relative to the declaring config file for upstream components or the component spec directory for local components. Required when origin type is 'custom'."`

	// MockPackages is a list of RPM package names to install in the mock chroot before
	// running [Origin.Script]. Only valid when [Origin.Type] is 'custom'.
	MockPackages []string `toml:"mock-packages,omitempty" json:"mockPackages,omitempty" jsonschema:"title=Mock packages,description=RPM packages to install in the mock chroot before running the generation script. Only valid when origin type is 'custom'."`

	// Inputs is a list of source-output filenames to copy next to [Origin.Script]
	// before it runs. Each entry must be a plain filename. Only valid when
	// [Origin.Type] is 'custom'.
	Inputs []string `toml:"inputs,omitempty" json:"inputs,omitempty" jsonschema:"title=Inputs,description=Source-output filenames to make available next to the generation script before it runs. Only valid when origin type is 'custom'."`
}

// EffectiveScriptName returns the checkout-independent filename of [Origin.Script].
func (o Origin) EffectiveScriptName() string {
	if o.Script == "" {
		return ""
	}

	return filepath.Base(o.Script)
}

// HashInclude implements the hashstructure [Includable] interface so that
// [Origin.Script], [Origin.MockPackages], and [Origin.Inputs] are omitted from
// the component fingerprint when they hold their zero values.
func (o Origin) HashInclude(field string, _ any) (bool, error) {
	switch field {
	case "Script":
		return o.Script != "", nil
	case "MockPackages":
		return len(o.MockPackages) > 0, nil
	case "Inputs":
		return len(o.Inputs) > 0, nil
	}

	return true, nil
}

// SourceFileReference encapsulates a reference to a specific source file artifact.
type SourceFileReference struct {
	// Reference to the component to which the source file belongs.
	Component ComponentReference `toml:"-" json:"-" fingerprint:"-"`

	// Name of the source file; must be non-empty.
	Filename string `toml:"filename" json:"filename"`

	// Hash of the source file, expressed as a hex string.
	Hash string `toml:"hash,omitempty" json:"hash,omitempty"`

	// Type of hash used by Hash (e.g., "SHA256", "SHA512").
	HashType fileutils.HashType `toml:"hash-type,omitempty" json:"hashType,omitempty" jsonschema:"enum=SHA256,enum=SHA512,title=Hash type,description=Hash algorithm used for the hash value"`

	// Origin for this source file. When omitted, the file is resolved via the lookaside cache.
	Origin Origin `toml:"origin,omitempty" json:"origin,omitempty"`

	// ReplaceUpstream, when true, intentionally replaces an upstream entry with the same
	// [SourceFileReference.Filename] in the dist-git 'sources' file. The matching upstream
	// entry must exist or source preparation fails. When false (the default), a filename
	// collision with an existing 'sources' entry is treated as an error.
	// [SourceFileReference.ReplaceReason] is required when this is true.
	ReplaceUpstream bool `toml:"replace-upstream,omitempty" json:"replaceUpstream,omitempty" jsonschema:"title=Replace upstream,description=When true\\, intentionally replaces a same-named entry in the upstream 'sources' file. Requires 'replace-reason'."`

	// ReplaceReason is a human-readable explanation for why an upstream 'sources' entry is
	// being replaced. Required when [SourceFileReference.ReplaceUpstream] is true; must be
	// empty otherwise. Excluded from the fingerprint because it is documentation only.
	ReplaceReason string `toml:"replace-reason,omitempty" json:"replaceReason,omitempty" jsonschema:"title=Replace reason,description=Required when 'replace-upstream' is true. Human-readable explanation for the replacement." fingerprint:"-"`
}

// ValidateArchiveOverlays validates archive/origin associations and prevents
// loose-file overlays from also modifying an archive that will be repacked.
// allowMissingOrigins supports '--allow-no-hashes' bootstrapping; orphaned
// overlay origins are always invalid.
func (c *ComponentConfig) ValidateArchiveOverlays(allowMissingOrigins bool) error {
	modifiedArchives := make(map[string]bool, len(c.Overlays))
	for _, overlay := range c.Overlays {
		if overlay.ModifiesArchive() {
			modifiedArchives[overlay.Archive] = true
		}
	}

	overlayOrigins := make(map[string]bool, len(c.SourceFiles))
	for _, sourceFile := range c.SourceFiles {
		if sourceFile.Origin.Type == OriginTypeOverlay && !modifiedArchives[sourceFile.Filename] {
			return fmt.Errorf(
				"'source-files' entry for %#q has 'origin.type = overlay', but no archive-scoped overlay modifies that archive; "+
					"add a matching archive overlay or remove the stale 'source-files' entry",
				sourceFile.Filename,
			)
		}

		if sourceFile.Origin.Type == OriginTypeOverlay {
			overlayOrigins[sourceFile.Filename] = true
		}
	}

	for archiveName := range modifiedArchives {
		if !allowMissingOrigins && !overlayOrigins[archiveName] {
			return fmt.Errorf(
				"archive overlay for %#q requires a matching 'source-files' entry with 'origin.type = overlay'; "+
					"add the entry to the component TOML, then run 'prepare-sources --allow-no-hashes' to bootstrap its hash",
				archiveName)
		}

		for _, overlay := range c.Overlays {
			matches, err := overlay.TargetsLooseFile(archiveName)
			if err != nil {
				return err
			}

			if matches {
				return fmt.Errorf(
					"loose-file %#q overlay targets archive %#q, which is also modified by an archive-scoped overlay; "+
						"an archive and its contents cannot be modified through both overlay scopes",
					overlay.Type, archiveName)
			}
		}
	}

	return nil
}

// HashInclude implements the hashstructure [Includable] interface so that
// [SourceFileReference.Origin] is omitted from the component fingerprint when
// none of [Origin.Script], [Origin.MockPackages], or [Origin.Inputs] are set.
func (r SourceFileReference) HashInclude(field string, _ any) (bool, error) {
	if field == "Origin" {
		return r.Origin.Script != "" || len(r.Origin.MockPackages) > 0 || len(r.Origin.Inputs) > 0, nil
	}

	return true, nil
}

// ComponentPublishConfig holds publish channel settings for a component's packages.
// The zero value means all channels are inherited from a higher-priority config layer.
type ComponentPublishConfig struct {
	// RPMChannel identifies the publish channel for binary (non-debuginfo) packages
	// produced by this component. When empty, the value is inherited from the next layer
	// in the resolution order.
	RPMChannel string `toml:"rpm-channel,omitempty" json:"rpmChannel,omitempty" validate:"omitempty,ne=.,ne=..,excludesall=/\\" jsonschema:"title=RPM channel,description=Publish channel for binary packages produced by this component"`

	// SRPMChannel identifies the publish channel for the SRPM produced by this component.
	// When empty, the value is inherited from the next layer in the resolution order.
	SRPMChannel string `toml:"srpm-channel,omitempty" json:"srpmChannel,omitempty" validate:"omitempty,ne=.,ne=..,excludesall=/\\" jsonschema:"title=SRPM channel,description=Publish channel for the SRPM produced by this component"`

	// DebugInfoChannel identifies the publish channel for debuginfo packages produced
	// by this component. When empty, the value is inherited from the next layer in the
	// resolution order.
	DebugInfoChannel string `toml:"debuginfo-channel,omitempty" json:"debuginfoChannel,omitempty" validate:"omitempty,ne=.,ne=..,excludesall=/\\" jsonschema:"title=Debuginfo channel,description=Publish channel for debuginfo packages produced by this component"`
}

// Defines a component group. Component groups are logical groupings of components (see [ComponentConfig]).
// A component group is useful because it allows for succinctly naming/identifying a curated set of components,
// say in a command line interface. Note that a component group does not uniquely "own" its components; a
// component may belong to multiple groups, and components need not belong to any group.
type ComponentGroupConfig struct {
	// A human-friendly description of this component group.
	Description string `toml:"description,omitempty" json:"description,omitempty" jsonschema:"title=Description,description=Description of this component group"`

	// Optional documentation metadata describing this component group's intent and provenance.
	// It reuses the overlay metadata schema (see [OverlayMetadata]) and does not affect how the
	// group's members are resolved or built.
	Metadata *OverlayMetadata `toml:"metadata,omitempty" json:"metadata,omitempty" jsonschema:"title=Metadata,description=Optional documentation metadata for this component group"`

	// List of explicitly included components, identified by name.
	Components []string `toml:"components,omitempty" json:"components,omitempty" jsonschema:"title=Components,description=List of component names that are members of this group"`

	// List of glob patterns specifying raw spec files that define components.
	SpecPathPatterns []string `toml:"specs,omitempty" json:"specs,omitempty" validate:"dive,required" jsonschema:"title=Spec path patterns,description=List of glob patterns identifying local specs for components in this group,example=SPECS/**/.spec"`
	// List of glob patterns specifying files to specifically ignore from spec selection.
	ExcludedPathPatterns []string `toml:"excluded-paths,omitempty" json:"excludedPaths,omitempty" jsonschema:"title=Excluded path patterns,description=List of glob patterns identifying local paths to exclude from spec selection,example=build/**"`

	// Default configuration to apply to component members of this group.
	DefaultComponentConfig ComponentConfig `toml:"default-component-config,omitempty" json:"defaultComponentConfig,omitempty" jsonschema:"title=Default component configuration,description=Default component config inherited by all members of this component group"`
}

// Returns a copy of the component group config with relative file paths converted to absolute
// file paths (relative to referenceDir, not the current working directory).
func (g ComponentGroupConfig) WithAbsolutePaths(referenceDir string) ComponentGroupConfig {
	// First deep-copy ourselves.
	//
	// NOTE: We use the panicking MustCopy() because copying should only fail if the input *type*
	// is invalid. Since we're always using the same type, we never expect to see a runtime error
	// here.
	result := deep.MustCopy(g)

	// Fix up paths.
	for i := range result.SpecPathPatterns {
		result.SpecPathPatterns[i] = makeAbsolute(referenceDir, result.SpecPathPatterns[i])
	}

	for i := range result.ExcludedPathPatterns {
		result.ExcludedPathPatterns[i] = makeAbsolute(referenceDir, result.ExcludedPathPatterns[i])
	}

	result.DefaultComponentConfig = *(result.DefaultComponentConfig.WithAbsolutePaths(referenceDir))

	return result
}

// ReleaseCalculation controls how the Release tag is managed during rendering.
type ReleaseCalculation string

const (
	// ReleaseCalculationAuto is the default. azldev auto-detects whether the spec uses
	// %autorelease or another Release form and handles each accordingly.
	ReleaseCalculationAuto ReleaseCalculation = "auto"

	// ReleaseCalculationAutorelease explicitly declares that the spec uses %autorelease.
	// azldev skips all Release tag manipulation, letting rpmautospec resolve the release
	// number from git history. Use this for specs with conditional %autorelease/%else
	// fallbacks that confuse auto-detection.
	ReleaseCalculationAutorelease ReleaseCalculation = "autorelease"

	// ReleaseCalculationStatic explicitly declares that the spec uses a non-%autorelease
	// release tag. azldev invokes rpmdev-bumpspec and accepts a mutation only when host
	// RPM evaluation proves the source Release is strictly newer.
	ReleaseCalculationStatic ReleaseCalculation = "static"

	// ReleaseCalculationManual skips all automatic Release tag manipulation. Use this for
	// components that manage their own release numbering (e.g. kernel).
	ReleaseCalculationManual ReleaseCalculation = "manual"
)

// ReleaseConfig holds release-related configuration for a component.
type ReleaseConfig struct {
	// Calculation controls how the Release tag is managed during rendering.
	Calculation ReleaseCalculation `toml:"calculation,omitempty" json:"calculation,omitempty" validate:"omitempty,oneof=auto autorelease static manual" jsonschema:"enum=auto,enum=autorelease,enum=static,enum=manual,default=auto,title=Release calculation,description=Controls how the Release tag is managed during rendering. Empty or omitted means auto."`
}

// FreshnessStatus indicates whether a component's current config matches
// its locked state. Computed at resolve time when freshness checking is
// enabled; [FreshnessUnknown] otherwise.
type FreshnessStatus int

const (
	// FreshnessUnknown means freshness was not computed (no lock, no stored
	// fingerprint, or freshness checking not requested).
	FreshnessUnknown FreshnessStatus = iota
	// FreshnessCurrent means both the input fingerprint and resolution hash
	// match the lock — the component is fully up-to-date.
	FreshnessCurrent
	// FreshnessStale means the recomputed fingerprint or resolution hash
	// differs from the lock — config, overlays, snapshot, or other inputs
	// changed since the last update.
	FreshnessStale
)

// String returns a human-readable label for the freshness status.
func (f FreshnessStatus) String() string {
	switch f {
	case FreshnessUnknown:
		return "unknown"
	case FreshnessCurrent:
		return "current"
	case FreshnessStale:
		return "stale"
	default:
		return "unknown"
	}
}

// ComponentLockData holds resolved lock file state attached to a component at
// resolve time. This separates user intent (config fields) from resolved reality
// (lock data). Populated by the component resolver from the lock store; nil when
// no lock file exists for this component.
//
// Not serialized to TOML config and not fingerprinted - runtime-only. The data
// IS included in JSON output (e.g., 'component list -O json') under "locked"
// so users can inspect resolved lock state. The pointer must not be shared
// across value-copied configs; the resolver always allocates a fresh struct
// per component, and [ComponentConfig.WithAbsolutePaths] deep-copies it.
type ComponentLockData struct {
	// UpstreamCommit is the resolved upstream commit from the lock file.
	UpstreamCommit string `json:"upstreamCommit,omitempty"`
	// ImportCommit is the upstream commit at fork time (write-once).
	ImportCommit string `json:"importCommit,omitempty"`
	// ManualBump is the extra rebuild counter.
	ManualBump int `json:"manualBump,omitempty"`
	// InputFingerprint is the stored fingerprint from the last update.
	// Covers build inputs (config, overlays, commit, manual bump, release ver)
	// but excludes resolution inputs like snapshot timestamp.
	InputFingerprint string `json:"inputFingerprint,omitempty"`
	// ResolutionInputHash is the stored hash of resolution inputs (snapshot,
	// distro ref, pin, upstream name). Used to determine if the locked commit
	// needs re-resolution.
	ResolutionInputHash string `json:"resolutionInputHash,omitempty"`
	// Freshness indicates whether the component's config matches its lock.
	// Runtime-only — computed by the resolver when freshness checking is enabled.
	Freshness FreshnessStatus `json:"-"`
	// ResolutionStale indicates whether resolution inputs specifically changed,
	// as opposed to build-only inputs. When true, re-resolution is needed.
	// When false but Freshness is Stale, only build inputs changed and the
	// locked commit can be reused.
	ResolutionStale bool `json:"-"`
}

// Defines a component.
type ComponentConfig struct {
	// The component's name; not actually present in serialized files.
	Name string `toml:"-" json:"name" table:",sortkey" fingerprint:"-"`

	// Reference to the source config file that this definition came from; not present
	// in serialized files.
	SourceConfigFile *ConfigFile `toml:"-" json:"-" table:"-" fingerprint:"-"`

	// RenderedSpecDir is the output directory for this component's rendered spec files.
	// Derived at resolve time from the project's rendered-specs-dir setting; not present
	// in serialized files. Empty when rendered-specs-dir is not configured.
	RenderedSpecDir string `toml:"-" json:"renderedSpecDir,omitempty" table:"-" fingerprint:"-"`

	// Locked holds resolved lock file state for this component. Populated by
	// the component resolver from the lock store. Nil when no lock file exists.
	// During 'component update', this field may be cleared before re-resolving
	// to prevent the source provider from short-circuiting with stale values.
	Locked *ComponentLockData `toml:"-" json:"locked,omitempty" table:"-" fingerprint:"-"`

	// Where to get its spec and adjacent files from.
	Spec SpecSource `toml:"spec,omitempty" json:"spec,omitempty" jsonschema:"title=Spec,description=Identifies where to find the spec for this component"`

	// Release configuration for this component.
	Release ReleaseConfig `toml:"release,omitempty" json:"release,omitempty" table:"-" jsonschema:"title=Release configuration,description=Configuration for how the Release tag is managed during rendering."`

	// Overlays to apply to sources after they've been acquired. May mutate the spec as well as sources.
	Overlays []ComponentOverlay `toml:"overlays,omitempty" json:"overlays,omitempty" table:"-" jsonschema:"title=Overlays,description=Overlays to apply to this component's spec and/or sources"`

	// OverlayFiles, if set, lists path or glob patterns (relative to this component config file)
	// matched against the filesystem after component config resolution to locate per-file overlay documents.
	// Each matched file is parsed as an [OverlayFile]: one logical change consisting of a
	// file-level `[metadata]` block plus an ordered list of `[[overlays]]`. The per-file
	// metadata is stamped onto every overlay in the file. Matches are concatenated in the
	// order patterns are declared; within a single pattern, matches are applied in
	// filename (lexicographic) order, using the full path as a tie-breaker when
	// filenames match. Duplicate matches are de-duplicated, preserving first
	// occurrence. The resulting overlays are appended to [ComponentConfig.Overlays]
	// after any inline overlays. A value set in a higher-priority config layer replaces
	// lower-priority overlay-files values; an explicit empty list disables inherited
	// overlay files. Excluded from the fingerprint because the value affects only where
	// overlays are sourced from, not their content.
	OverlayFiles []string `toml:"overlay-files,omitempty" json:"overlayFiles,omitempty" table:"-" validate:"dive,required" jsonschema:"title=Overlay files,description=Path or glob patterns (relative to the component config file or matched spec directory) matched against the filesystem to locate per-file overlay documents after component config resolution. Use an empty list to disable inherited overlay-file patterns" fingerprint:"-"`

	// Configuration for building the component.
	Build ComponentBuildConfig `toml:"build,omitempty" json:"build,omitempty" table:"-" jsonschema:"title=Build configuration,description=Configuration for building the component"`

	// Configuration for rendering the component.
	Render ComponentRenderConfig `toml:"render,omitempty" json:"render,omitempty" table:"-" jsonschema:"title=Render configuration,description=Configuration for rendering the component"`

	// Source file references for this component.
	SourceFiles []SourceFileReference `toml:"source-files,omitempty" json:"sourceFiles,omitempty" table:"-" jsonschema:"title=Source files,description=Source files to download for this component"`

	// Per-package configuration overrides, keyed by exact binary package name.
	// Takes precedence over package-group defaults.
	Packages map[string]PackageConfig `toml:"packages,omitempty" json:"packages,omitempty" table:"-" validate:"dive" jsonschema:"title=Package overrides,description=Per-package configuration overrides keyed by exact binary package name"`

	// Publish holds the component-level publish settings. These provide default channels for
	// all packages produced by this component. Overridden by package-group and per-package settings
	// for binary and debuginfo channels.
	Publish ComponentPublishConfig `toml:"publish,omitempty" json:"publish,omitempty" table:"-" jsonschema:"title=Publish settings,description=Component-level publish channel settings" fingerprint:"-"`

	// Tests holds the new-shape per-component tests block:
	//
	//   tests.tests = [{ name = "..." }, { group = "..." }]
	//
	// References must resolve to entries in the project-level [tests] or
	// [test-groups] maps; resolution is the responsibility of the test layer.
	Tests *ComponentTestsConfig `toml:"tests,omitempty" json:"tests,omitempty" table:"-" jsonschema:"title=Tests,description=Per-component test or test-group references" fingerprint:"-"`
}

// AllowedSourceFilesHashTypes defines the set of hash types that are supported
// for use in [SourceFileReference] entries in component configs.
// MD5 is excluded by design.
//
//nolint:gochecknoglobals // This is effectively a constant, but Go doesn't have const maps.
var AllowedSourceFilesHashTypes = map[fileutils.HashType]bool{
	fileutils.HashTypeSHA256: true,
	fileutils.HashTypeSHA512: true,
}

// Mutates the component config, updating it with overrides present in other.
func (c *ComponentConfig) MergeUpdatesFrom(other *ComponentConfig) error {
	otherOverlayFiles := slices.Clone(other.OverlayFiles)

	err := mergo.Merge(c, other, mergo.WithOverride, mergo.WithAppendSlice)
	if err != nil {
		return fmt.Errorf("failed to merge project info:\n%w", err)
	}

	if other.OverlayFiles != nil {
		c.OverlayFiles = otherOverlayFiles
	}

	return nil
}

func (c *ComponentConfig) resolveLocalCustomScriptPaths() {
	if c.Spec.SourceType != SpecSourceTypeLocal || c.Spec.Path == "" {
		return
	}

	scriptDir := filepath.Dir(c.Spec.Path)
	for i := range c.SourceFiles {
		origin := &c.SourceFiles[i].Origin
		if origin.Type == OriginTypeCustom && origin.Script != "" {
			origin.Script = filepath.Join(scriptDir, origin.EffectiveScriptName())
		}
	}
}

// EffectiveUpstreamCommit returns the commit to use for upstream operations.
// Prefers the locked commit (resolved reality) over the config pin (user intent).
// Falls back to Spec.UpstreamCommit for SkipLockValidation paths (update, list,
// changed) where Locked may be nil. Returns empty string when neither is set.
func (c *ComponentConfig) EffectiveUpstreamCommit() string {
	if c.Locked != nil && c.Locked.UpstreamCommit != "" {
		return c.Locked.UpstreamCommit
	}

	return c.Spec.UpstreamCommit
}

// ResolveComponentConfig applies the full config inheritance chain for a single component:
// distro defaults → project-level defaults → group defaults (sorted) → component explicit config.
// Returns a fully resolved copy; the inputs are not modified.
// On error the returned config is undefined and must not be used.
func ResolveComponentConfig(
	comp ComponentConfig,
	projectDefaults ComponentConfig,
	distroDefaults ComponentConfig,
	groups map[string]ComponentGroupConfig,
	groupMembership []string,
) (ComponentConfig, error) {
	merged := deep.MustCopy(distroDefaults)

	if err := merged.MergeUpdatesFrom(&projectDefaults); err != nil {
		return ComponentConfig{}, fmt.Errorf("failed to apply project defaults:\n%w", err)
	}

	// Apply group defaults in sorted order for determinism.
	sortedGroups := slices.Clone(groupMembership)
	sort.Strings(sortedGroups)

	for _, groupName := range sortedGroups {
		groupConfig, ok := groups[groupName]
		if !ok {
			return ComponentConfig{}, fmt.Errorf("component group not found: %#q", groupName)
		}

		if err := merged.MergeUpdatesFrom(&groupConfig.DefaultComponentConfig); err != nil {
			return ComponentConfig{}, fmt.Errorf(
				"failed to apply defaults from component group %#q:\n%w",
				groupName, err)
		}
	}

	if err := merged.MergeUpdatesFrom(&comp); err != nil {
		return ComponentConfig{}, fmt.Errorf("failed to apply component config:\n%w", err)
	}

	merged.resolveLocalCustomScriptPaths()

	return merged, nil
}

// Returns a copy of the component config with relative file paths converted to absolute
// file paths (relative to referenceDir, not the current working directory).
func (c *ComponentConfig) WithAbsolutePaths(referenceDir string) *ComponentConfig {
	// Deep copy the input to avoid unexpected sharing. Make sure *not* to deep-copy
	// the SourceConfigFile, as we *do* want to alias that pointer, sharing it across
	// all configs that came from that source config file.
	result := &ComponentConfig{
		Name:             c.Name,
		SourceConfigFile: c.SourceConfigFile,
		RenderedSpecDir:  c.RenderedSpecDir,
		Locked:           deep.MustCopy(c.Locked),
		Release:          c.Release,
		Spec:             deep.MustCopy(c.Spec),
		Build:            deep.MustCopy(c.Build),
		Render:           c.Render,
		SourceFiles:      deep.MustCopy(c.SourceFiles),
		Packages:         deep.MustCopy(c.Packages),
		Publish:          deep.MustCopy(c.Publish),
		// OverlayFiles is consumed after component config resolution; preserve it verbatim
		// here so inherited patterns can be interpreted relative to the concrete component
		// config file.
		OverlayFiles: slices.Clone(c.OverlayFiles),
		Tests:        deep.MustCopy(c.Tests),
	}

	// Fix up paths.
	result.Spec.Path = makeAbsolute(referenceDir, result.Spec.Path)

	for i := range result.SourceFiles {
		origin := &result.SourceFiles[i].Origin
		if origin.Type == OriginTypeCustom {
			origin.Script = makeAbsolute(referenceDir, origin.Script)
		}
	}

	// Copy and fix up overlays.
	if c.Overlays != nil {
		result.Overlays = make([]ComponentOverlay, len(c.Overlays))

		for i := range result.Overlays {
			result.Overlays[i] = *c.Overlays[i].WithAbsolutePaths(referenceDir)
		}
	}

	return result
}

// IsDebugInfoPackage reports whether pkgName is a debuginfo or debugsource package.
// It matches "-debuginfo" or "-debugsource" as hyphen-delimited segments so that
// names like "kernel-debuginfo-common-x86_64" are correctly identified while
// unrelated packages like "elfutils-debuginfod" are not.
func IsDebugInfoPackage(pkgName string) bool {
	return containsRPMSegment(pkgName, "-debuginfo") || containsRPMSegment(pkgName, "-debugsource")
}

// containsRPMSegment reports whether pkgName contains segment as a hyphen-delimited
// segment — i.e. segment is followed by end-of-string or '-'. This prevents
// "-debuginfo" from matching "-debuginfod".
func containsRPMSegment(pkgName, segment string) bool {
	searchStart := 0

	for {
		idx := strings.Index(pkgName[searchStart:], segment)
		if idx < 0 {
			return false
		}

		idx += searchStart
		end := idx + len(segment)

		if end == len(pkgName) || pkgName[end] == '-' {
			return true
		}

		searchStart = idx + 1
	}
}

// ResolvePackagePublishChannel returns the publish channel for a binary package produced by a
// component. The caller must pass a resolved [ComponentConfig] (one whose Publish field already
// reflects project-level, distro, and component-group defaults).
//
// Resolution order (later wins):
//  0. The project-level default package config ([ProjectConfig.DefaultPackageConfig]), used
//     only as a fallback when all higher-priority sources produce an empty channel.
//  1. The resolved component-level publish channel ([ComponentPublishConfig.RPMChannel] or
//     [ComponentPublishConfig.DebugInfoChannel], depending on the package name).
//  2. The matching package-group's publish channel, if the package belongs to one.
//  3. The component's explicit per-package publish channel override, if set.
func ResolvePackagePublishChannel(pkgName string, comp *ComponentConfig, proj *ProjectConfig) (string, error) {
	isDebugInfo := IsDebugInfoPackage(pkgName)

	// Lowest priority: project-level default package config acts as a fallback for
	// packages not covered by any higher-priority source. This matches the old
	// single-field 'publish.channel' behaviour where the default applied to all packages.
	channel := packagePublishChannel(&proj.DefaultPackageConfig.Publish, isDebugInfo)

	// Component-level channel overrides the project default.
	var compChannel string
	if isDebugInfo {
		compChannel = comp.Publish.DebugInfoChannel
	} else {
		compChannel = comp.Publish.RPMChannel
	}

	if compChannel != "" {
		channel = compChannel
	}

	// Apply package-group override if this package belongs to one.
	for _, group := range proj.PackageGroups {
		if slices.Contains(group.Packages, pkgName) {
			if groupChannel := packagePublishChannel(&group.DefaultPackageConfig.Publish, isDebugInfo); groupChannel != "" {
				channel = groupChannel
			}

			break
		}
	}

	// Apply the explicit per-package override (highest priority).
	if pkgConfig, ok := comp.Packages[pkgName]; ok {
		if pkgChannel := packagePublishChannel(&pkgConfig.Publish, isDebugInfo); pkgChannel != "" {
			channel = pkgChannel
		}
	}

	return channel, nil
}

// packagePublishChannel returns the rpm-channel or debuginfo-channel from publish config
// depending on whether the package is a debuginfo package. For non-debuginfo packages,
// it falls back to the deprecated 'channel' field for backwards compatibility.
func packagePublishChannel(publish *PackagePublishConfig, isDebugInfo bool) string {
	if isDebugInfo {
		return publish.DebugInfoChannel
	}

	return publish.EffectiveRPMChannel()
}
